
from bot.locals import Local

LOCAL = Local({
    'WRONG_ROOM' : 'I a\'m Not Suppose to be Here.\nID • <code>{CHAT_ID}</code>',
    'WELCOME_MESSAGE' : "Hi !\nI'm <b>Assistant Bot</b> !\nOwned & Powered by <b><a href='https://t.me/Go_odbye'>Anuj Dakhore</a></b>",
    'PASS_REQUIRED' : '\n\nUse <code>/{cmd_pass} </code> to Enter The Password For Your Verification.',
    'LEECH_LIST_MESSAGE_HEADER' : '<b>Leech Status</b>',
    'LEECH_LIST_FORMAT' : 'Name • <code>{name}</code>\nStatus • {status}\nID • <code>{gid}</code>\n\n',
    'ARIA2_CHECKING_LINK' : "Checking... .. .",
    'ARIA2_DOWNLOAD_STATUS' : "Downloading • <code>{name}</code>\nProgress • {block}\nPercentage • {percentage}%\nSize • {total_size}\nSpeed • ⬇ {download_speed} || ⬆ {upload_speed}\nSeeder • {seeder}\nETA • {eta}\nID • <code>{gid}</code>",
    'ARIA2_DOWNLOAD_SUCCESS' : 'File Downloaded Successfully • \n<code>{name}</code>',
    'ARIA2_DOWNLOAD_CANCELED' : 'Sorry 😔, Your Download Was Cancelled • \n<code>{name}</code>',
    'ARIA2_DEAD_LINK' : 'Sorry 😔, Your Download Was Auto-Cancelled • \n<code>{name}</code>\nYour Torrent / Link is Dead.',
    'ARIA2_NO_URI' : 'Link is invalid.',
    'UPLOADING_FILE' : 'Uploading • \n<code>{name}</code>',
    'UPLOADING_PROGRESS' : 'Uploading • <code>{name}</code>\nProgress • {block}\nPercentage • {percentage}%\nSize • {size}\nSpeed • {upload_speed}/s\nETA • {eta}',
    'UPLOAD_FAILED_FILE_MISSING' : 'Upload • Failed. \n<code>{name}</code> \n<b>ERROR</b> • <code>404 - File Not Found</code>.',
    'GENERATE_THUMBNAIL' : 'Thumbnail • Generating... .. . \n<code>{name}</code>',
    'SPLIT_FILE' : 'Spliting • <code>{name}</code>',
    'SPLIT_FAILED' : 'Split • Failed.\n<code>{name}</code>',
    'THUMBNAIL_NO_PHOTO' : 'Set <code>/{cmd_set_thumbnail}</code> as Your Photo Caption.',
    'THUMBNAIL_DOWNLOADING' : 'Downloading Your Thumbnail... .. .',
    'THUMBNAIL_DOWNLOADED' : 'Thumbnail Downloaded Successfully.',
    'THUMBNAIL_APPLIED' : 'Thumbnail is Successfully Applied For Your Future Uploads.',
    'THUMBNAIL_DELETING' : 'Resetting Thumbnail... .. .',
    'THUMBNAIL_RESET' : 'Thumbnail is Successfully Reset For Your Future Uploads.',
    'UPLOAD_AS_DOC' : 'Upload as Document Set to {status}.',
    'UPLOAD_AS_ZIP' : 'Upload as .zip File Set to {status}.',
    'TRACKER_RESET' : 'Default Torrent Tracker Reset.',
    'TRACKER_APPLIED' : 'Default Torrent Tracker Applied.',
    'HELP_MESSAGE_HEADER' : '<b>Bot Commands</b>',
    'NO_HELP_INFO' : 'no information',
    'COMMAND_START' : 'To Check Bot Alive / Dead',
    'COMMAND_PASSWORD' : 'Enter Password To Verify You',
    'COMMAND_HELP' : 'For Detail Information',
    'COMMAND_LEECH' : 'Reply To Direct Download Link or Magnet Link',
    'COMMAND_CANCEL_LEECH' : 'Cancel Mirroring',
    'COMMAND_LEECH_LIST' : 'List of Mirroring Processes',
    'COMMAND_SET_THUMBNAIL' : 'To Set Custom Thumbnail',
    'COMMAND_RESET_THUMBNAIL' : 'To Reset Custom Thumbnail',
    'COMMAND_UPLOAD_AS_DOC' : 'Toggle Uploading Streaming / Document Type',
    'COMMAND_UPLOAD_AS_ZIP' : 'Toggle Uploading Bundled Zipfile / Separated Single File',
    'COMMAND_SET_TRACKER' : 'To Set Default Tracker For Magnet Links. If You Want Set Multiple Tracker Then Send Each Tracker Per Line in a Single Message.',
    'BLOCK_EMPTY' : "▱",
    "BLOCK_FILLED" : "▰"
})
